version: '2'

services:
    web:
        image: nginx
        environment:
            - TERM=xterm
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/estagio.conf:/etc/nginx/conf.d/estagio.conf
            - .:/estagio
            - ./docker/php/index.php:/estagio/index.php
        ports:
            - "8089:8080" # PHP Info
            - "81:80" # WEB
        links:
            - php
            - mariadb
    php:
        image: tuxmate/php:5.5.9
        tty: true
        environment:
            - TERM=xterm
        volumes:
            - ./docker/php/www.conf:/etc/php5/fpm/pool.d/www.conf
            - ./docker/php/php.ini:/etc/php5/fpm/php.ini
            - .:/estagio
            - ./docker/php/index.php:/estagio/index.php
    mariadb:
        image: mariadb:10.1.18
        environment:
            - TERM=xterm
            - MYSQL_ROOT_PASSWORD=32130
            - MYSQL_DATABASE=usuario
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "3306:3306"
